name: Code Coverage

on:
  push:
    paths:
      - "GENetLib/*.py"
      - "pytest/*.py"
      - ".github/workflows/code_coverage.yml"
  pull_request:
    paths:
      - "GENetLib/*.py"
      - "pytest/*.py"
      - ".github/workflows/code_coverage.yml"
  workflow_dispatch:

jobs:
  codecovPy:
    name: Codecov workflow
    runs-on: windows-latest
    env:
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install GENetLib & dependencies
        run: |
          pip install -e .
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          cd ./pytest
          pytest --cov=GENetLib -v --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./pytest/coverage.xml
          verbose: true
